In [1]:
import numpy as np
from PIL import Image, ImageDraw
from homography_util import *

# Method 2 - projective distortion
img1 = np.array(Image.open("1.jpg"))
L1 = np.array([1044,869,1])
L2 = np.array([1025,1030,1])
M1 = np.array([2024,420,1])
M2 = np.array([2038,619,1])
P1 = np.array([2024,420,1])
P2 = np.array([1044,869,1])
Q1 = np.array([2038,619,1])
Q2 = np.array([1025,1030,1])
l = np.cross(L1, L2) 
m = np.cross(M1, M2)
p = np.cross(P1, P2)
q = np.cross(Q1, Q2)
VP1 = np.cross(l, m) ; VP1 = VP1 / VP1[2]
VP2 = np.cross(p, q) ; VP2 = VP2 / VP2[2]
VL = np.cross(VP1, VP2) ; VL = VL / VL[2]
H_p = np.array([[1,0,0],[0,1,0],[VL[0],VL[1],VL[2]]])
print("(VP1,VP2,VL) = ", VP1,VP2,VL)
print("H_p = ", H_p)
(x_min,y_min,mapped_img1) = Mapped(img1, H_p)
mapped = Image.fromarray(np.uint8(mapped_img1), 'RGB')
mapped.save("img1-m21.jpg")

# Method 2 - affine distortion (mapped_img1 as a start)
draw_img12 = Image.open("img1-m21.jpg")
draw = ImageDraw.Draw(draw_img12)
R1 = np.array([108,546,1]) 
R2 = np.array([97,579,1]) 
S1 = np.array([108,546,1]) 
S2 = np.array([124,527,1]) 
T1 = np.array([425,318,1]) 
T2 = np.array([389,358,1]) 
U1 = np.array([425,318,1]) 
U2 = np.array([442,275,1]) 
draw.line((R1[0], R1[1], R2[0], R2[1]), fill=(255,0,0), width = 5)
draw.line((S1[0], S1[1], S2[0], S2[1]), fill=(255,0,0), width = 5)
draw.line((T1[0], T1[1], T2[0], T2[1]), fill=(255,0,0), width = 5)
draw.line((U1[0], U1[1], U2[0], U2[1]), fill=(255,0,0), width = 5)
draw_img12.save("img1-m22-annotaton.jpg")
r = np.cross(R1, R2); 
s = np.cross(S1, S2); 
t = np.cross(T1, T2); 
u = np.cross(U1, U2);
print("(r,s,t,u)=", r, s, t, u)
lhs = np.array([[r[0]*s[0], r[0]*s[1]+r[1]*s[0]], [t[0]*u[0], t[0]*u[1]+t[1]*u[0]]])
rhs = np.array([[-r[1]*s[1]],[-t[1]*u[1]]])
v_tmp = np.matmul(np.linalg.inv(lhs), rhs)
v_tmp2 = np.array([[v_tmp[0][0],v_tmp[1][0]],[v_tmp[1][0],1]])
sigma, U = np.linalg.eig(v_tmp2)
A = np.matmul(U, np.diag(np.sqrt(sigma)))*(-1)
print("Sanity check: a_11 = ", A[0][0], 
      ", a_11*a_22-a_12*a_21 = ", A[0][0]*A[1][1]-A[0][1]*A[1][0])
H_a = np.zeros((3,3))
H_a[2][2] = 1
H_a[0:2,0:2] = np.linalg.inv(A)
print("H_a = ", H_a)
(x_min,y_min,mapped2_img1) = Mapped(mapped_img1, H_a)
mapped = Image.fromarray(np.uint8(mapped2_img1), 'RGB')
mapped.save("img1-m22.jpg")

(VP1,VP2,VL) =  [ 1.67777200e+03 -4.50138376e+03  1.00000000e+00] [-1.87930177e+03  2.20834948e+03  1.00000000e+00] [1.41128253e-03 7.48172225e-04 1.00000000e+00]
H_p =  [[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [1.41128253e-03 7.48172225e-04 1.00000000e+00]]
(r,s,t,u)= [ -33  -11 9570] [    19     16 -10788] [  -40   -36 28448] [    43     17 -23681]
Sanity check: a_11 =  0.1770128414577271 , a_11*a_22-a_12*a_21 =  0.25142742231331794
H_a =  [[ 3.95040249  2.59062911  0.        ]
 [-0.46169591  0.70403156  0.        ]
 [ 0.          0.          1.        ]]


In [2]:
img2 = np.array(Image.open("2.jpg"))
L1 = np.array([232,57,1])
L2 = np.array([231,281,1])
M1 = np.array([338,73,1])
M2 = np.array([336,278,1])
P1 = np.array([232,57,1])
P2 = np.array([338,73,1])
Q1 = np.array([231,281,1])
Q2 = np.array([336,278,1])
l = np.cross(L1, L2)
m = np.cross(M1, M2)
p = np.cross(P1, P2)
q = np.cross(Q1, Q2)
VP1 = np.cross(l, m) ; VP1 = VP1 / VP1[2]
VP2 = np.cross(p, q) ; VP2 = VP2 / VP2[2]
VL = np.cross(VP1, VP2) ; VL = VL / VL[2]
H_p = np.array([[1,0,0],[0,1,0],[VL[0],VL[1],VL[2]]])
print("(VP1,VP2,VL) = ", VP1,VP2,VL)
print("H_p = ", H_p)
(x_min,y_min,mapped_img2) = Mapped(img2, H_p)
mapped = Image.fromarray(np.uint8(mapped_img2), 'RGB')
mapped.save("img2-m21.jpg")

# Method 2 - affine distortion (mapped_img1 as a start)
draw_img22 = Image.open("img2-m21.jpg")
draw = ImageDraw.Draw(draw_img22)
R1 = np.array([275,68,1]) 
R2 = np.array([277,343,1]) 
S1 = np.array([275,68,1]) 
S2 = np.array([439,91,1]) 
T1 = np.array([643,330,1]) 
T2 = np.array([548,319,1]) 
U1 = np.array([643,330,1]) 
U2 = np.array([639,225,1]) 
draw.line((R1[0], R1[1], R2[0], R2[1]), fill=(255,0,0), width = 5)
draw.line((S1[0], S1[1], S2[0], S2[1]), fill=(255,0,0), width = 5)
draw.line((T1[0], T1[1], T2[0], T2[1]), fill=(255,0,0), width = 5)
draw.line((U1[0], U1[1], U2[0], U2[1]), fill=(255,0,0), width = 5)
draw_img22.save("img2-m22-annotaton.jpg")
r = np.cross(R1, R2); 
s = np.cross(S1, S2); 
t = np.cross(T1, T2); 
u = np.cross(U1, U2);
print("(r,s,t,u)=", r, s, t, u)
lhs = np.array([[r[0]*s[0], r[0]*s[1]+r[1]*s[0]], [t[0]*u[0], t[0]*u[1]+t[1]*u[0]]])
rhs = np.array([[-r[1]*s[1]],[-t[1]*u[1]]])
v_tmp = np.matmul(np.linalg.inv(lhs), rhs)
v_tmp2 = np.array([[v_tmp[0][0],v_tmp[1][0]],[v_tmp[1][0],1]])
sigma, U = np.linalg.eig(v_tmp2)
A = np.matmul(U, np.diag(np.sqrt(sigma)))
print("Sanity check: a_11 = ", A[0][0], 
      ", a_11*a_22-a_12*a_21 = ", A[0][0]*A[1][1]-A[0][1]*A[1][0])
H_a = np.zeros((3,3))
H_a[2][2] = 1
H_a[0:2,0:2] = np.linalg.inv(A)
print("H_a = ", H_a)
(x_min,y_min,mapped2_img2) = Mapped(mapped_img2, H_a)
mapped = Image.fromarray(np.uint8(mapped2_img2), 'RGB')
mapped.save("img2-m22.jpg")

(VP1,VP2,VL) =  [1.42444444e+02 2.01174444e+04 1.00000000e+00] [1.47964865e+03 2.45324324e+02 1.00000000e+00] [-6.68379216e-04 -4.49755483e-05  1.00000000e+00]
H_p =  [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-6.68379216e-04 -4.49755483e-05  1.00000000e+00]]
(r,s,t,u)= [ -275     2 75489] [  -23   164 -4827] [   11   -95 24277] [   105     -4 -66195]
Sanity check: a_11 =  1.0152866433896997 , a_11*a_22-a_12*a_21 =  1.0967557209861098
H_a =  [[ 0.76162483  0.4124137   0.        ]
 [-0.50126889  0.92571812  0.        ]
 [ 0.          0.          1.        ]]


In [3]:
img3 = np.array(Image.open("3.jpg"))
draw_img31 = Image.open("3.jpg")
draw = ImageDraw.Draw(draw_img31)
L1 = np.array([1404,855,1])
L2 = np.array([1425,1557,1])
M1 = np.array([3309,855,1])
M2 = np.array([3243,1947,1])
P1 = np.array([2991,456,1])
P2 = np.array([1917,615,1])
Q1 = np.array([2841,2664,1])
Q2 = np.array([1833,2289,1])
draw.line((L1[0], L1[1], L2[0], L2[1]), fill=(255,0,0), width = 20)
draw.line((M1[0], M1[1], M2[0], M2[1]), fill=(255,0,0), width = 20)
draw.line((P1[0], P1[1], P2[0], P2[1]), fill=(0,0,255), width = 20)
draw.line((Q1[0], Q1[1], Q2[0], Q2[1]), fill=(0,0,255), width = 20)
draw_img31.save("img3-m21-annotaton.jpg")
l = np.cross(L1, L2)
m = np.cross(M1, M2)
p = np.cross(P1, P2)
q = np.cross(Q1, Q2)
VP1 = np.cross(l, m) ; VP1 = VP1 / VP1[2]
VP2 = np.cross(p, q) ; VP2 = VP2 / VP2[2]
VL = np.cross(VP1, VP2) ; VL = VL / VL[2]
H_p = np.array([[1,0,0],[0,1,0],[VL[0],VL[1],VL[2]]])
print("(VP1,VP2,VL) = ", VP1,VP2,VL)
print("H_p = ", H_p)
(x_min,y_min,mapped_img3) = Mapped(img3, H_p)
mapped = Image.fromarray(np.uint8(mapped_img3), 'RGB')
mapped.save("img3-m21.jpg")

# Method 2 - affine distortion (mapped_img1 as a start)
draw_img32 = Image.open("img3-m21.jpg")
draw = ImageDraw.Draw(draw_img32)
R1 = np.array([567,516,1]) 
R2 = np.array([339,684,1]) 
S1 = np.array([567,516,1]) 
S2 = np.array([600,968,1]) 
T1 = np.array([305,1701,1]) 
T2 = np.array([284,1425,1]) 
U1 = np.array([305,1701,1]) 
U2 = np.array([464,1575,1]) 
draw.line((R1[0], R1[1], R2[0], R2[1]), fill=(255,0,0), width = 20)
draw.line((S1[0], S1[1], S2[0], S2[1]), fill=(255,0,0), width = 20)
draw.line((T1[0], T1[1], T2[0], T2[1]), fill=(255,0,0), width = 20)
draw.line((U1[0], U1[1], U2[0], U2[1]), fill=(255,0,0), width = 20)
draw_img32.save("img3-m22-annotaton.jpg")
r = np.cross(R1, R2); 
s = np.cross(S1, S2); 
t = np.cross(T1, T2); 
u = np.cross(U1, U2);
print("(r,s,t,u)=", r, s, t, u)
lhs = np.array([[r[0]*s[0], r[0]*s[1]+r[1]*s[0]], [t[0]*u[0], t[0]*u[1]+t[1]*u[0]]])
rhs = np.array([[-r[1]*s[1]],[-t[1]*u[1]]])
v_tmp = np.matmul(np.linalg.inv(lhs), rhs)
v_tmp2 = np.array([[v_tmp[0][0],v_tmp[1][0]],[v_tmp[1][0],1]])
sigma, U = np.linalg.eig(v_tmp2)
A = np.matmul(U, np.diag(np.sqrt(sigma)))*(-1)
print("Sanity check: a_11 = ", A[0][0], 
      ", a_11*a_22-a_12*a_21 = ", A[0][0]*A[1][1]-A[0][1]*A[1][0])
H_a = np.zeros((3,3))
H_a[2][2] = 1
H_a[0:2,0:2] = np.linalg.inv(A)
print("H_a = ", H_a)
(x_min,y_min,mapped2_img3) = Mapped(mapped_img3, H_a)
mapped = Image.fromarray(np.uint8(mapped2_img3), 'RGB')
mapped.save("img3-m22.jpg")

(VP1,VP2,VL) =  [2.03470946e+03 2.19387162e+04 1.00000000e+00] [-1.36189498e+03  1.10042300e+03  1.00000000e+00] [ 6.48818974e-04 -1.05756330e-04  1.00000000e+00]
H_p =  [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 6.48818974e-04 -1.05756330e-04  1.00000000e+00]]
(r,s,t,u)= [  -168   -228 212904] [  -452     33 239256] [   276    -21 -48459] [    126     159 -308889]
Sanity check: a_11 =  0.24062670739386532 , a_11*a_22-a_12*a_21 =  0.24088325309343392
H_a =  [[ 4.15125668 -0.13755507  0.        ]
 [ 0.03310048  0.99893498  0.        ]
 [ 0.          0.          1.        ]]


In [4]:
img4 = np.array(Image.open("4.jpg"))
draw_img41 = Image.open("4.jpg")
draw = ImageDraw.Draw(draw_img41)
L1 = np.array([1254,1353,1])
L2 = np.array([1428,1929,1])
M1 = np.array([1884,825,1])
M2 = np.array([2133,1428,1])
P1 = np.array([1671,681,1])
P2 = np.array([1341,1071,1])
Q1 = np.array([2112,1749,1])
Q2 = np.array([1653,2058,1])
draw.line((L1[0], L1[1], L2[0], L2[1]), fill=(255,0,0), width = 20)
draw.line((M1[0], M1[1], M2[0], M2[1]), fill=(255,0,0), width = 20)
draw.line((P1[0], P1[1], P2[0], P2[1]), fill=(0,0,255), width = 20)
draw.line((Q1[0], Q1[1], Q2[0], Q2[1]), fill=(0,0,255), width = 20)
draw_img41.save("img4-m21-annotaton.jpg")
l = np.cross(L1, L2)
m = np.cross(M1, M2)
p = np.cross(P1, P2)
q = np.cross(Q1, Q2)
VP1 = np.cross(l, m) ; VP1 = VP1 / VP1[2]
VP2 = np.cross(p, q) ; VP2 = VP2 / VP2[2]
VL = np.cross(VP1, VP2) ; VL = VL / VL[2]
H_p = np.array([[1,0,0],[0,1,0],[VL[0],VL[1],VL[2]]])
print("(VP1,VP2,VL) = ", VP1,VP2,VL)
print("H_p = ", H_p)
(x_min,y_min,mapped_img4) = Mapped(img4, H_p)
mapped = Image.fromarray(np.uint8(mapped_img4), 'RGB')
mapped.save("img4-m21.jpg")

# Method 2 - affine distortion (mapped_img1 as a start)
draw_img42 = Image.open("img4-m21.jpg")
draw = ImageDraw.Draw(draw_img42)
R1 = np.array([651,207,1]) 
R2 = np.array([604,384,1]) 
S1 = np.array([651,207,1]) 
S2 = np.array([680,379,1]) 
T1 = np.array([558,563,1]) 
T2 = np.array([575,663,1]) 
U1 = np.array([558,563,1]) 
U2 = np.array([582,470,1]) 
draw.line((R1[0], R1[1], R2[0], R2[1]), fill=(255,0,0), width = 20)
draw.line((S1[0], S1[1], S2[0], S2[1]), fill=(255,0,0), width = 20)
draw.line((T1[0], T1[1], T2[0], T2[1]), fill=(255,0,0), width = 20)
draw.line((U1[0], U1[1], U2[0], U2[1]), fill=(255,0,0), width = 20)
draw_img42.save("img4-m22-annotaton.jpg")
r = np.cross(R1, R2); 
s = np.cross(S1, S2); 
t = np.cross(T1, T2); 
u = np.cross(U1, U2);
print("(r,s,t,u)=", r, s, t, u)
lhs = np.array([[r[0]*s[0], r[0]*s[1]+r[1]*s[0]], [t[0]*u[0], t[0]*u[1]+t[1]*u[0]]])
rhs = np.array([[-r[1]*s[1]],[-t[1]*u[1]]])
v_tmp = np.matmul(np.linalg.inv(lhs), rhs)
v_tmp2 = np.array([[v_tmp[0][0],v_tmp[1][0]],[v_tmp[1][0],1]])
sigma, U = np.linalg.eig(v_tmp2)
A = np.matmul(U, np.diag(np.sqrt(sigma)))*(-1)
print("Sanity check: a_11 = ", A[0][0], 
      ", a_11*a_22-a_12*a_21 = ", A[0][0]*A[1][1]-A[0][1]*A[1][0])
H_a = np.zeros((3,3))
H_a[2][2] = 1
H_a[0:2,0:2] = np.linalg.inv(A)
print("H_a = ", H_a)
(x_min,y_min,mapped2_img4) = Mapped(mapped_img4, H_a)
mapped = Image.fromarray(np.uint8(mapped2_img4), 'RGB')
mapped.save("img4-m22.jpg")

(VP1,VP2,VL) =  [-1.05697055e+03 -6.29710940e+03  1.00000000e+00] [-1.01252453e+03  3.85243808e+03  1.00000000e+00] [ 9.71444586e-04 -4.25406552e-06  1.00000000e+00]
H_p =  [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 9.71444586e-04 -4.25406552e-06  1.00000000e+00]]
(r,s,t,u)= [  -177    -47 124956] [  -172     29 105969] [ -100    17 46229] [    93     24 -65406]
Sanity check: a_11 =  0.1553117410639569 , a_11*a_22-a_12*a_21 =  0.15697118322168468
H_a =  [[ 6.36976491 -0.66246979  0.        ]
 [ 0.10290276  0.98942836  0.        ]
 [ 0.          0.          1.        ]]


In [5]:
# For bonus, "bonus_image.jpg"
L1 = np.array([90,678,1])    # Black pairs
L2 = np.array([1842,309,1])
M1 = np.array([459,1443,1])
M2 = np.array([2331,930,1])
P1 = np.array([726,2472,1])  # Blue pairs
P2 = np.array([1491,735,1])
Q1 = np.array([2619,2679,1])
Q2 = np.array([2697,906,1])
l = np.cross(L1, L2)
m = np.cross(M1, M2)
p = np.cross(P1, P2)
q = np.cross(Q1, Q2)
VP1 = np.cross(l, m) ; VP1 = VP1 / VP1[2]
VP2 = np.cross(p, q) ; VP2 = VP2 / VP2[2]
VL = np.cross(VP1, VP2) ; VL = VL / VL[2]
print("(l,m,p,q) = ", l,m,p,q)
print("(VP1,VP2,VL) = ", VP1,VP2,VL)

L1 = np.array([765,1842,1])  # Red pairs
L2 = np.array([273,402,1])
M1 = np.array([2058,1305,1])
M2 = np.array([1305,294,1])
P1 = np.array([1131,2397,1])   # Green pairs
P2 = np.array([129,1398,1])
Q1 = np.array([1929,1287,1])
Q2 = np.array([543,378,1])
l = np.cross(L1, L2)
m = np.cross(M1, M2)
p = np.cross(P1, P2)
q = np.cross(Q1, Q2)
VP1 = np.cross(l, m) ; VP1 = VP1 / VP1[2]
VP2 = np.cross(p, q) ; VP2 = VP2 / VP2[2]
VL = np.cross(VP1, VP2) ; VL = VL / VL[2]
print("(l,m,p,q) = ", l,m,p,q)
print("(VP1,VP2,VL) = ", VP1,VP2,VL)

(l,m,p,q) =  [     369     1752 -1221066] [     513     1872 -2936763] [    1737      765 -3152142] [    1773       78 -4852449]
(VP1,VP2,VL) =  [ 1.37464579e+04 -2.19827453e+03  1.00000000e+00] [ 2.83919471e+03 -2.32619504e+03  1.00000000e+00] [-4.97056376e-06  4.23819837e-04  1.00000000e+00]
(l,m,p,q) =  [   1440    -492 -195336] [    1011     -753 -1097973] [    999   -1002 1271925] [  909 -1386 30321]
(VP1,VP2,VL) =  [-6.69806355e+02 -2.35743323e+03  1.00000000e+00] [-3.65665056e+03 -2.37631628e+03  1.00000000e+00] [-2.68658632e-06  4.24953495e-04  1.00000000e+00]
